### ISSUE TITLE
v2: http marshal funcs are not generated for second level nested type 

### ISSUE THREAD

**Issue by tmcladam** [goadesign/goa#2126]
Use this design to reproduce :

[repro.go.txt](https://github.com/goadesign/goa/files/3231190/repro.go.txt)

Error message from go test ./... :

```
# github.com/flexera/trs-ingest/ingest_service/gen/http/public/server
http/public/server/encode_decode.go:62:13: undefined: unmarshalMissingRequestBodyToPublicMissing
# github.com/flexera/trs-ingest/ingest_service/gen/http/public/client
http/public/client/encode_decode.go:93:14: undefined: marshalPublicMissingToMissingRequestBody
http/public/client/encode_decode.go:105:14: undefined: marshalMissingRequestBodyToPublicMissing
```

**Comment by tmcladam** [comment]
This appears to be introduced in https://github.com/goadesign/goa/pull/2121

**Comment by tmcladam** [comment]
Thanks - this fixes the original issue but the attached slightly tweaked version, this time with an ArrayOf() in the payload, is still failing with the same error. Should I create a new issue?

[repro3.go.txt](https://github.com/goadesign/goa/files/3235818/repro3.go.txt)

**Comment by raphael** [comment]
ugh no it's fine - I'll just reopen this one, thank you!

**Comment by tmcladam** [comment]
3.0.2 is working for us now - thanks!
